[strava]
client_id =
client_secret =
redirect_url = 
authorize_url = "https://www.strava.com/oauth/authorize"
token_url = "https://www.strava.com/oauth/token"
refresh_token_url = "https://www.strava.com/oauth/token"
revoke_token_url = "https://www.strava.com/oauth/deauthorize"
scope = "activity:read_all,read"
